GRAPH_SIZE = (800, 800)
GRAPH_BOUNDARIES = ((0, 0), (1000, 1000))
GRAPH_PADDING = 20
GRAPH_COORDS_BOTTOM_LEFT = (0 - GRAPH_PADDING, 0 - GRAPH_PADDING)
GRAPH_COORDS_TOP_RIGHT = (GRAPH_BOUNDARIES[1][0] +
                          GRAPH_PADDING, GRAPH_BOUNDARIES[1][1] + GRAPH_PADDING)
